const imgSrc = './src/img';

export const cardData = [
    { imgSrc: `${imgSrc}/6-Clubs.png`, name: '6-Clubs' },
    { imgSrc: `${imgSrc}/6-Diamonds.png`, name: '6-Diamonds' },
    { imgSrc: `${imgSrc}/6-Hearts.png`, name: '6-Hearts' },
    { imgSrc: `${imgSrc}/6-Spades.png`, name: '6-Spades' },
    { imgSrc: `${imgSrc}/7-Clubs.png`, name: '7-Clubs' },
    { imgSrc: `${imgSrc}/7-Diamonds.png`, name: '7-Diamonds' },
    { imgSrc: `${imgSrc}/7-Hearts.png`, name: '7-Hearts' },
    { imgSrc: `${imgSrc}/7-Spades.png`, name: '7-Spades' },
    { imgSrc: `${imgSrc}/8-Clubs.png`, name: '8-Clubs' },
    { imgSrc: `${imgSrc}/8-Diamonds.png`, name: '8-Diamonds' },
    { imgSrc: `${imgSrc}/8-Hearts.png`, name: '8-Hearts' },
    { imgSrc: `${imgSrc}/8-Spades.png`, name: '8-Spades' },
    { imgSrc: `${imgSrc}/9-Clubs.png`, name: '9-Clubs' },
    { imgSrc: `${imgSrc}/9-Diamonds.png`, name: '9-Diamonds' },
    { imgSrc: `${imgSrc}/9-Hearts.png`, name: '9-Hearts' },
    { imgSrc: `${imgSrc}/9-Spades.png`, name: '9-Spades' },
    { imgSrc: `${imgSrc}/10-Clubs.png`, name: '10-Clubs' },
    { imgSrc: `${imgSrc}/10-Diamonds.png`, name: '10-Diamonds' },
    { imgSrc: `${imgSrc}/10-Hearts.png`, name: '10-Hearts' },
    { imgSrc: `${imgSrc}/10-Spades.png`, name: '10-Spades' },
    { imgSrc: `${imgSrc}/Ace-Clubs.png`, name: 'Ace-Clubs' },
    { imgSrc: `${imgSrc}/Ace-Diamonds.png`, name: 'Ace-Diamonds' },
    { imgSrc: `${imgSrc}/Ace-Hearts.png`, name: 'Ace-Hearts' },
    { imgSrc: `${imgSrc}/Ace-Spades.png`, name: 'Ace-Spades' },
    { imgSrc: `${imgSrc}/Jack-Clubs.png`, name: 'Jack-Clubs' },
    { imgSrc: `${imgSrc}/Jack-Diamonds.png`, name: 'Jack-Diamonds' },
    { imgSrc: `${imgSrc}/Jack-Hearts.png`, name: 'Jack-Hearts' },
    { imgSrc: `${imgSrc}/Jack-Spades.png`, name: 'Jack-Spades' },
    { imgSrc: `${imgSrc}/King-Clubs.png`, name: 'King-Clubs' },
    { imgSrc: `${imgSrc}/King-Diamonds.png`, name: 'King-Diamonds' },
    { imgSrc: `${imgSrc}/King-Hearts.png`, name: 'King-Hearts' },
    { imgSrc: `${imgSrc}/King-Spades.png`, name: 'King-Spades' },
    { imgSrc: `${imgSrc}/Queen-Clubs.png`, name: 'Queen-Clubs' },
    { imgSrc: `${imgSrc}/Queen-Diamonds.png`, name: 'Queen-Diamonds' },
    { imgSrc: `${imgSrc}/Queen-Hearts.png`, name: 'Queen-Hearts' },
    { imgSrc: `${imgSrc}/Queen-Spades.png`, name: 'Queen-Spades' },
];
